services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-backend
    restart: unless-stopped
    ports:
      - "5005:5005"
    environment:
      - NODE_ENV=production

  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: http://backend:3000
    container_name: admin-frontend
    restart: unless-stopped
    ports:
      - "3001:3000"
    depends_on:
      - backend
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://backend:3000
