version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production

  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile
    container_name: admin-frontend
    restart: unless-stopped
    ports:
      - "3001:3000"
    volumes:
      - ./admin:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
